name: CI/CD Pipeline for Static Website

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (optional, if you need it for tools like html-proofer)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use Node.js 16

      # Step 3: Install dependencies (e.g., html-proofer)
      - name: Install dependencies
        run: npm install

      # Step 4: Validate HTML files
      - name: Validate HTML
        run: npx htmlproofer ./ --allow-hash-href --check-html --empty-alt-ignore

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          publish_dir: ./  # Directory to deploy (root of the repository)
